# Generated by Django 4.1 on 2022-08-15 08:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('first_name', models.CharField(max_length=25)),
                ('last_name', models.CharField(max_length=25)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(blank=True, default='', max_length=20)),
                ('mobile', models.CharField(blank=True, default='', max_length=20)),
                ('company_name', models.CharField(max_length=250)),
                ('is_confirmed_client', models.BooleanField(default=False, verbose_name='Confirmed client')),
                ('sales_contact', models.ForeignKey(blank=True, limit_choices_to={'role': 'COMMERCIAL'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='clients', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='EventStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name_plural': 'Event status',
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('attendees', models.PositiveIntegerField(default=0)),
                ('event_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, help_text='Important notes')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events_client', to='api.client')),
                ('event_status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events_status', to='api.eventstatus')),
                ('support_contact', models.ForeignKey(blank=True, limit_choices_to={'role': 'SUPPORT'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='events_support', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['client'],
            },
        ),
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('status', models.BooleanField(default=False, verbose_name='Contract signed')),
                ('amount', models.FloatField(verbose_name='Amount (€)')),
                ('payment_due', models.DateField(blank=True, null=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clients', to='api.client')),
                ('event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='events_contract', to='api.event')),
                ('sales_contact', models.ForeignKey(blank=True, limit_choices_to={'role': 'COMMERCIAL'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='commercials', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['client'],
            },
        ),
    ]
