# Generated by Django 4.1 on 2022-08-10 08:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0003_contract'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contract',
            options={'ordering': ['client']},
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('attendees', models.PositiveIntegerField(default=0)),
                ('event_status', models.CharField(choices=[('FUTURE', 'Future event'), ('IN PROGRESS', 'Event in progress'), ('ENDED', 'Event ended')], max_length=20)),
                ('event_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, help_text='Important notes')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events_client', to='api.client')),
                ('support_contact', models.ForeignKey(blank=True, limit_choices_to={'role': 'SUPPORT'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='events_support', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['client'],
            },
        ),
    ]
