# Generated by Django 4.1 on 2022-08-11 14:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_eventstatus_alter_event_event_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='event',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='events_contract', to='api.event'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='payment_due',
            field=models.DateField(blank=True, null=True),
        ),
    ]
